/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AwardTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    DISTANCE_BASED: 'distance_based',

    /**
     * TODO: Write general description for this element
     */
    FARE_BASED: 'fare_based',

};

module.exports = AwardTypeEnum;
