/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const CabinTypeEnum = {

    /**
     * First Class Discounted
     */
    A: 'A',

    /**
     * Economy/Coach
     */
    B: 'B',

    /**
     * Business Class
     */
    C: 'C',

    /**
     * Business Class Discounted
     */
    D: 'D',

    /**
     * Shuttle Service (no reservation allowed) or Economy/Coach Discounted
     */
    E: 'E',

    /**
     * First Class
     */
    F: 'F',

    /**
     * Conditional Reservation
     */
    G: 'G',

    /**
     * Economy/Coach Discounted
     */
    H: 'H',

    /**
     * Business Class Premium
     */
    J: 'J',

    /**
     * Economy/Coach Discounted
     */
    K: 'K',

    /**
     * Economy/Coach Discounted
     */
    L: 'L',

    /**
     * Economy/Coach Discounted
     */
    M: 'M',

    /**
     * Economy/Coach Discounted
     */
    N: 'N',

    /**
     * First Class Premium
     */
    P: 'P',

    /**
     * Economy/Coach Discounted
     */
    Q: 'Q',

    /**
     * First Class Suite or Supersonic (discontinued)
     */
    R: 'R',

    /**
     * Economy/Coach
     */
    S: 'S',

    /**
     * Economy/Coach Discounted
     */
    T: 'T',

    /**
     * Shuttle Service
     */
    U: 'U',

    /**
     * Economy/Coach Discounted
     */
    V: 'V',

    /**
     * Economy/Coach Premium
     */
    W: 'W',

    /**
     * Economy/Coach Discounted
     */
    X: 'X',

    /**
     * Economy/Coach
     */
    Y: 'Y',

    /**
     * Business Class Discounted
     */
    Z: 'Z',

};

module.exports = CabinTypeEnum;
