/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const CabinTypeEnum = {

    /**
     * Unknown
     */
    UNKNOWN: 'unknown',

    /**
     * Discount Economy
     */
    DISCOUNT_ECONOMY: 'discount_economy',

    /**
     * Economy
     */
    ECONOMY: 'economy',

    /**
     * Full Economy
     */
    FULL_ECONOMY: 'full_economy',

    /**
     * Premium Economy
     */
    PREMIUM_ECONOMY: 'premium_economy',

    /**
     * Discount Business
     */
    DISCOUNT_BUSINESS: 'discount_business',

    /**
     * Business
     */
    BUSINESS: 'business',

    /**
     * Premium Business
     */
    PREMIUM_BUSINESS: 'premium_business',

    /**
     * First
     */
    FIRST: 'first',

    /**
     * Premium First
     */
    PREMIUM_FIRST: 'premium_first',

};

module.exports = CabinTypeEnum;
