/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const CardTypeEnum = {

    /**
     * Unknown
     */
    UNKNOWN: 'unknown',

    /**
     * Basic
     */
    BASIC: 'basic',

    /**
     * Red
     */
    RED: 'red',

    /**
     * Silver
     */
    SILVER: 'silver',

    /**
     * Gold
     */
    GOLD: 'gold',

    /**
     * Platinum
     */
    PLATINUM: 'platinum',

    /**
     * Diamond
     */
    DIAMOND: 'diamond',

    /**
     * Corparate
     */
    CORPARATE: 'corparate',

};

module.exports = CardTypeEnum;
