/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ExtraInfoTypeEnum = {

    /**
     * Nationality
     */
    NATIONALITY: 'nationality',

    /**
     * National ID Number
     */
    NATIONAL_ID_NUMBER: 'national_id_number',

    /**
     * Language
     */
    LANGUAGE: 'language',

    /**
     * Gender
     */
    GENDER: 'gender',

    /**
     * Birthday
     */
    BIRTHDAY: 'birthday',

    /**
     * Academic Title
     */
    ACADEMIC_TITLE: 'academic_title',

    /**
     * Address
     */
    ADDRESS: 'address',

    /**
     * Country
     */
    COUNTRY: 'country',

    /**
     * City
     */
    CITY: 'city',

    /**
     * Area
     */
    AREA: 'area',

    /**
     * Zip Code
     */
    ZIP_CODE: 'zip_code',

    /**
     * Password
     */
    PASSWORD: 'password',

};

module.exports = ExtraInfoTypeEnum;
