/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const FlightStatusTypeEnum = {

    /**
     * Used
     */
    USED: 'used',

    /**
     * Unused
     */
    UNUSED: 'unused',

    /**
     * Reissued
     */
    REISSUED: 'reissued',

};

module.exports = FlightStatusTypeEnum;
