/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of FlightSimple
 */
class FlightSimple extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.airline = this.constructor.getValue(obj.airline);
        this.pnr = this.constructor.getValue(obj.pnr);
        this.departureDate = this.constructor.getValue(obj.departureDate || obj.departure_date);
        this.departureAirport =
          this.constructor.getValue(obj.departureAirport
     || obj.departure_airport);
        this.arrivalAirport = this.constructor.getValue(obj.arrivalAirport || obj.arrival_airport);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'airline', realName: 'airline' },
            { name: 'pnr', realName: 'pnr' },
            { name: 'departureDate', realName: 'departure_date' },
            { name: 'departureAirport', realName: 'departure_airport' },
            { name: 'arrivalAirport', realName: 'arrival_airport' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = FlightSimple;
