/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Response = require('./Response');

/**
 * Creates an instance of FlightStatusResponse
 */
class FlightStatusResponse extends Response {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.flightStatus = this.constructor.getValue(obj.flightStatus || obj.flight_status);
        this.flight = this.constructor.getValue(obj.flight);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'flightStatus', realName: 'flight_status' },
            { name: 'flight', realName: 'flight', type: 'FlightMax' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = FlightStatusResponse;
