/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of FlightCreateRequest
 */
class FlightCreateRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.awardMilesRules =
          this.constructor.getValue(obj.awardMilesRules
     || obj.award_miles_rules);
        this.passenger = this.constructor.getValue(obj.passenger);
        this.routingType = this.constructor.getValue(obj.routingType || obj.routing_type);
        this.flights = this.constructor.getValue(obj.flights);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'awardMilesRules', realName: 'award_miles_rules', type: 'AwardMilesRules' },
            { name: 'passenger', realName: 'passenger', type: 'PassengerMax' },
            { name: 'routingType', realName: 'routing_type' },
            { name: 'flights', realName: 'flights', array: true, type: 'FlightMax' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = FlightCreateRequest;
