/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const GenderTypeEnum = {

    /**
     * Male
     */
    MALE: 'male',

    /**
     * Female
     */
    FEMALE: 'female',

    /**
     * Unknown
     */
    UNKNOWN: 'unknown',

};

module.exports = GenderTypeEnum;
