/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const LanguageTypeEnum = {

    /**
     * for English
     */
    EN: 'en',

    /**
     * for Turkish
     */
    TR: 'tr',

};

module.exports = LanguageTypeEnum;
