/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of MemberSearchRequest
 */
class MemberSearchRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.ffpNumber = this.constructor.getValue(obj.ffpNumber || obj.ffp_number);
        this.firstName = this.constructor.getValue(obj.firstName || obj.first_name);
        this.lastName = this.constructor.getValue(obj.lastName || obj.last_name);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'ffpNumber', realName: 'ffp_number' },
            { name: 'firstName', realName: 'first_name' },
            { name: 'lastName', realName: 'last_name' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = MemberSearchRequest;
