/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Response = require('./Response');

/**
 * Creates an instance of MemberSearchResponse
 */
class MemberSearchResponse extends Response {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.cardType = this.constructor.getValue(obj.cardType || obj.card_type);
        this.baseMiles = this.constructor.getValue(obj.baseMiles || obj.base_miles);
        this.promoMiles = this.constructor.getValue(obj.promoMiles || obj.promo_miles);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'cardType', realName: 'card_type' },
            { name: 'baseMiles', realName: 'base_miles' },
            { name: 'promoMiles', realName: 'promo_miles' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
        };
    }
}

module.exports = MemberSearchResponse;
