/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const RoutingTypeEnum = {

    /**
     * One way trip indicator.
     */
    ONE_WAY: 'one_way',

    /**
     * Round trip indicator.
     */
    ROUND_TRIP: 'round_trip',

};

module.exports = RoutingTypeEnum;
