/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const TierTypeEnum = {

    /**
     * Unknown
     */
    UNKNOWN: 'unknown',

    /**
     * Basic
     */
    BASIC: 'basic',

    /**
     * Red
     */
    TIER_1: 'tier1',

    /**
     * Silver
     */
    TIER_2: 'tier2',

    /**
     * Gold
     */
    TIER_3: 'tier3',

    /**
     * Platinum
     */
    TIER_4: 'tier4',

    /**
     * Diamond
     */
    TIER_5: 'tier5',

    /**
     * Corparate
     */
    TIER_6: 'tier6',

};

module.exports = TierTypeEnum;
