/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Environments = {

    /**
     * TODO: Write general description for this element
     */
    TEST: 'Test',

};

module.exports = Environments;
