/**
 * GlobalMilesAirlineAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Environments = {

    /**
     * Cloud Environment
     */
    CLOUD: 'Cloud',

};

module.exports = Environments;
